config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'infos', to: 'pages#infos'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def infos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LifeSaver</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container home">
  <h2 class="text-center">What is Life Saver ?</h2>
  <article>
    <p>Ut enim benefici liberalesque sumus, non ut exigamus gratiam (neque enim beneficium faeneramur sed natura propensi ad liberalitatem sumus), sic amicitiam non spe mercedis adducti sed quod omnis eius fructus in ipso amore inest, expetendam putamus.</p>
    <p>Quam ob rem cave Catoni anteponas ne istum quidem ipsum, quem Apollo, ut ais, sapientissimum iudicavit; huius enim facta, illius dicta laudantur. De me autem, ut iam cum utroque vestrum loquar, sic habetote.</p>
    <p>Oportunum est, ut arbitror, explanare nunc causam, quae ad exitium praecipitem Aginatium inpulit iam inde a priscis maioribus nobilem, ut locuta est pertinacior fama. nec enim super hoc ulla documentorum rata est fides.</p>
  </article>
</div>

app/views/pages/infos.html.erb
<section class="care container">
  <h2 class="text-center title2">Life Saver</h2>
  <article>
    <p>Excitavit hic ardor milites per municipia plurima, quae isdem conterminant, dispositos et castella, sed quisque serpentes latius pro viribus repellere moliens, nunc globis confertos, aliquotiens et dispersos multitudine superabatur ingenti, quae nata et educata inter editos recurvosque ambitus montium eos ut loca plana persultat et mollia, missilibus obvios eminus lacessens et ululatu truci perterrens.</p>
  </article>
  <div class="cards">
    <div class="card-product">
      <i class="fas fa-star-of-life fa-3x"></i>
      <div class="card-product-infos">
        <h2>GROUPE SANGUIN</h2>
        <p>Product description with <strong>relevant info</strong> only.</p>
      </div>
    </div>
    <div class="card-product">
      <i class="fas fa-user fa-3x"></i>
      <div class="card-product-infos">
        <h2>INFORMATIONS PERSONNELLES</h2>
        <p>Product description with <strong>relevant info</strong> only.</p>
      </div>
    </div>
    <div class="card-product">
      <i class="fas fa-allergies fa-3x"></i>
      <div class="card-product-infos">
        <h2>ALLERGIES</h2>
        <p>Product description with <strong>relevant info</strong> only.</p>
      </div>
    </div>
    <div class="card-product">
      <i class="fas fa-heart fa-3x"></i>
      <div class="card-product-infos">
        <h2>PERSONNE A CONTACTER</h2>
        <p>Product description with <strong>relevant info</strong> only.</p>
      </div>
    </div>
    <div class="card-product">
      <i class="fas fa-briefcase-medical fa-3x"></i>
      <div class="card-product-infos">
        <h2>ANTECEDENTS</h2>
        <p>Product description with <strong>relevant info</strong> only.</p>
      </div>
    </div>
    <div class="card-product">
      <i class="fas fa-user-friends fa-3x"></i>
      <div class="card-product-infos">
        <h2>PARENTS</h2>
        <p>Product description with <strong>relevant info</strong> only.</p>
      </div>
    </div>
    <div class="card-product">
      <i class="fas fa-syringe fa-3x"></i>
      <div class="card-product-infos">
        <h2>VACCINS</h2>
        <p>Product description with <strong>relevant info</strong> only.</p>
      </div>
    </div>
    <div class="card-product">
      <i class="fas fa-user-md fa-3x"></i>
      <div class="card-product-infos">
        <h2>MEDECIN</h2>
        <p>Product description with <strong>relevant info</strong> only.</p>
      </div>
    </div>
    <div class="card-product">
      <i class="fas fa-baby fa-3x"></i>
      <div class="card-product-infos">
        <h2>AGE</h2>
        <p>Product description with <strong>relevant info</strong> only.</p>
      </div>
    </div>
    <div class="card-product">
      <i class="fas fa-clinic-medical fa-3x"></i>
      <div class="card-product-infos">
        <h2>ASSURANCE</h2>
        <p>Product description with <strong>relevant info</strong> only.</p>
      </div>
    </div>
  </div>
</section>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <p>&copy; Copyright 2021</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
  <div class="mx-auto">
    <div class="title">
      <h1>LIFE SAVER</h1>
    </div>
    <!-- Navbar links -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav link">
        <%= link_to "Acceuil", root_path, class: "navbar-brand nav-item"%>
        <%= link_to "Mes infos", infos_path, class: "navbar-brand nav-item"%>
      </div>
    </div>
  </div>
</nav>
<!--
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
<%= link_to "Login", new_user_session_path, class: "nav-link" %>
</li>
      <% end %>
    </ul>
  </div>
</div>
-->
<%= link_to "Login", new_user_session_path, class: "nav-link" %>